### ISSUE TITLE
add hasOne / belongsToMany as aliases of belongsTo / hasMany

### ISSUE THREAD

**Issue by Leooo** [miragejs/server#19]
@samselikoff , would you take a PR adding `hasOne` & `belongsToMany` relationships, that would just behave like aliases of `belongsTo` / `hasMany` in Mirage?

=> running some scripts on our domain model here, and need to order by child / parent so useful to specify in the relationships if only for doc purposes (I also believe there may be some room to destroy children as opposed to parents when deleting a model in some cases in Mirage but that would not be part of this PR).

**Comment by samselikoff** [comment]
Not sure I follow... literally new imports that behave the same way?

```
import { hasOne } from 'ember-cli-mirage';
```

like that?

**Comment by Leooo** [comment]
Yes, that's what I would have in mind.

**Comment by samselikoff** [comment]
Why not
```
import { belongsTo as hasOne } from 'ember-cli-mirage';`
```
?

**Comment by Leooo** [comment]
@samselikoff I was hoping for something simple like that yes. Are saying it just works as of now if I import like that in my app? 🥇

**Comment by Leooo** [comment]
I guess I can just try and it will, closing this issue before I forget and thanking you a lot for the tip which is always obvious once you know it. Think it should be in all wikis of the world that you can just do that.

**Comment by samselikoff** [comment]
Yep, that's part of the ES6 module spec! https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Syntax
