### ISSUE TITLE
Mirage is not re-patching fetch/XMLHttpRequest after hot reloading

### ISSUE THREAD

**Issue by asantos00** [miragejs/server#37]
While using @miragejs/server with a vuejs app, I encountered a issue that happens after live-reloading.

The `fetch` function was being *hot reloaded* after changing the code and (I suppose) it was not getting *re-patched* by pretenderjs and thus the newly defined routes weren't being detected.

After a proper refresh, they worked.

This is a pretty common usecase for react/vuejs apps and so it looks like we wanna fix it.

**Comment by danielgek** [comment]
@asantos00 was able to reproduce!

If somehow you get a mirage error(in my case was about having `http://localhost:3000/` as `this.namespace`) and then  you update your config(let's say changing the `this.namespace` to `/`) the fetch is never "repatched"

**Comment by danielgek** [comment]
Just re-tested with latest version and it seems fixed, tried a few options and it patched successfully, thanks you mates!

**Comment by samselikoff** [comment]
Excellent!
