### ISSUE TITLE
Get Jest to run eslint

### ISSUE THREAD

**Issue by samselikoff** [miragejs/server#42]
Tried setting this up, but jest eslint runner disagreed with what `eslint` from the CLI did (which was the same as what my editor did).

It does seem to be reading `.eslintrc.js` but for some reason disagrees? Not sure

**Comment by ryanto** [comment]
https://github.com/miragejs/server/pull/58

**Comment by samselikoff** [comment]
https://github.com/miragejs/server/pull/58 closes
