### ISSUE TITLE
Need to be able to treat collection as array

### ISSUE THREAD

**Issue by patrickberkeley** [miragejs/server#52]
`Collection` exposes one array method `length`, but a common pattern is to clone the array of data by calling `toArray()` on the collection of models. This is not currently possible since the models array is nested inside of `Collection`.

Can/will you expose other array methods so a collection can be treated as an array?

**Comment by samselikoff** [comment]
It's still basically impossible to truly subclass arrays in JS which is why we chose to go the route of exposing the models as a true array via `models`. I usually recommend `collection.models.[arrayMethod]` as an escape hatch. That being said we do have filter/sort/slice on there so I'm in favor of adding additional methods.

(One problem we ran into in the past was folks getting confused Collections were actual true arrays, so they'd reasonably pass them into things like lodash array functions only to hit very strange and confusing errors. So that's a concern too.)

What's the use case you ran into? Wanting to do something like `[...collection]`?

**Comment by patrickberkeley** [comment]
The use case is nested components:

The parent model has a has-many relationship, that gets passed into an outer component e.g.,

### App code
#### Context consuming outer component
```hbs
<Outer @book={{model}}>
```
#### Outer component template
```hbs
<Inner @chapters={{book.chapters}}>
```
#### Inner component JS
```js
@computed('chapters.[]')
get transformedData() {
  return this.chapters.toArray().map(...);
}
```
### Test code
```js
this.book = this.server.create('book');
this.chapters = this.server.createList('chapter', 3, { book });
```

The tests blow up because we have passed `books.chapters` down into the child and called `toArray()` and `map()` on it in the JS file. For app code this works because they are in the store, but test code errors because chapters mirage `Collection` doesn't have all the array methods.

**Comment by samselikoff** [comment]
Mmm, I see what's happened. You should not be doing this with Mirage - Mirage models are really intended for the "server" and shouldn't be passed to Ember components.

Give this a read (the second called "Creating Ember Data models on the client with Mirage") and let me know if it makes sense: https://www.ember-cli-mirage.com/docs/testing/integration-and-unit-tests#creating-ember-data-models-on-the-client-with-mirage

**Comment by patrickberkeley** [comment]
✅ understood and fixed. Thank you.

**Comment by timbakkum** [comment]
Forgive me for commenting on a closed issue, but I love mirage and i'm using it to generate fixtures for my unit test input but wondering what the best way is to get the raw data (array of objects in this case) without the extra mirage functions tagged on like `find` that overwrite the existing array methods. 

I've come so far:

```javascript
mockserver.createList('fileRaw', 10);
const files: FileData[] = Array.from(mockserver.schema.db.fileRaws);
const result = someFn(files);
// assert on result
```

Is there a better way? I found that `Array.from(mockserver.db['fileRaws'])` also works but it is not intuitive to do this as an inexperienced mirage users in my team.

**Comment by samselikoff** [comment]
If you want to get everything in the database try ‘server.db.dump’. This will give you the data in Mirage’s raw db format (camelCase, foreign keys and such). If you want to go through your serializer layer try ‘server.serialize(modelOrCollection).
