### ISSUE TITLE
replace the Lodash with individual lodash packages

### ISSUE THREAD

**Issue by mehulkar** [miragejs/server#75]
Carried over from https://github.com/samselikoff/ember-cli-mirage/issues/1699

**Comment by jayzhou3** [comment]
Let me know when you fix that thank you

**Comment by mehulkar** [comment]
@jayzhou3 #77 has a start, if you're familiar with Jest, maybe you could take it over the finish line?

**Comment by samselikoff** [comment]
https://github.com/miragejs/server/pull/77 closes
